import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Login From",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='flex justify-center items-center w-screen h-screen'>{children}</body>
    </html>
  );
}
